"""short description

Revision ID: 7640c93f2e8f
Revises: 2812cdb72478
Create Date: 2025-09-02 11:06:53.709645
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7640c93f2e8f'
down_revision = '2812cdb72478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_custom_profiles', sa.Column('cap_details', sa.Text(), nullable=True), schema='plugin_custom_profile_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_custom_profiles', 'cap_details', schema='plugin_custom_profile_fields')
    # ### end Alembic commands ###
