"""short description

Revision ID: 2812cdb72478
Revises: 
Create Date: 2025-08-29 13:43:56.261941
"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.sql.ddl import CreateSchema, DropSchema

# revision identifiers, used by Alembic.
revision = '2812cdb72478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSchema('plugin_custom_profile_fields'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_custom_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('shirt_size', sa.String(), nullable=True),
    sa.Column('dietary_options', sa.JSON(), nullable=True),
    sa.Column('dietary_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('fk_user_custom_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_custom_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_custom_profiles_user_id')),
    schema='plugin_custom_profile_fields'
    )
    op.create_index(op.f('ix_user_custom_profiles_user_id'), 'user_custom_profiles', ['user_id'], unique=False, schema='plugin_custom_profile_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_custom_profiles_user_id'), table_name='user_custom_profiles', schema='plugin_custom_profile_fields')
    op.drop_table('user_custom_profiles', schema='plugin_custom_profile_fields')
    # ### end Alembic commands ###
    op.execute(DropSchema('plugin_custom_profile_fields'))
