#!/usr/bin/env python3

# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""Migration to separate legal name.

Separate legal name into first and last name.
Remove field_surname from mapping as it is unnecessary.

Revision ID: 7ca9a88f8f2f
Revises: 3b609596bb71
Create Date: 2025-12-11 23:10:37.121996
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ca9a88f8f2f"
down_revision = "3b609596bb71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add legal_first and legal_last fields, remove legal_name and field_surname."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_field_mapping", "field_surname", schema="plugin_custom_profile_fields")
    op.add_column(
        "user_custom_profiles",
        sa.Column("legal_first", sa.String(), nullable=True),
        schema="plugin_custom_profile_fields",
    )
    op.add_column(
        "user_custom_profiles",
        sa.Column("legal_last", sa.String(), nullable=True),
        schema="plugin_custom_profile_fields",
    )
    op.drop_column("user_custom_profiles", "legal_name", schema="plugin_custom_profile_fields")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert legal_first and legal_last fields, add legal_name and field_surname."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_custom_profiles",
        sa.Column("legal_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="plugin_custom_profile_fields",
    )
    op.drop_column("user_custom_profiles", "legal_last", schema="plugin_custom_profile_fields")
    op.drop_column("user_custom_profiles", "legal_first", schema="plugin_custom_profile_fields")
    op.add_column(
        "custom_field_mapping",
        sa.Column("field_surname", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="plugin_custom_profile_fields",
    )
    # ### end Alembic commands ###
